from game.shared.color import Color
from game.shared.point import Point

#GAME
GAME_NAME = "Space Invaders"
DEFAULT_LIVES = 3
FRAME_RATE = 30

#SCREEN 
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 900
CENTER_X = SCREEN_WIDTH / 2
CENTER_Y = SCREEN_HEIGHT / 2
COLUMNS = 60 
ROWS = 40
CELL_SIZE = 25
FONT_SIZE = 25

#COLORS
BLACK = Color(0, 0, 0)
WHITE_B = Color(255, 255, 255, 55)
WHITE = Color(255, 255, 255)
RED = Color(255, 0, 0)
BLUE = Color(0, 0, 255)
GREEN = Color(0, 255, 0)

#ENEMIES
DEFAULT_ENEMIES = 40
ENEMIES = ["@"]
ENEMIES_VELOCITY = Point(1, 0)
ENEMIES_VELOCITY2 = Point(0, 1) 

#BACKGROUND
DEFAULT_BACKGROUND_OBJECTS = 75
BACKGROUND = ["*", "o",]
BACKGROUND_VELOCITY = Point(0, 3)

#LASER
LASER_VELOCITY = Point(0, -3)